### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by fnemani** [zaucy/rules_7zip#3]
Open your WORKSPACE FILE and add

http_archive(
    name = "com_github_zaucy_rules_7zip",
    strip_prefix = "rules_7zip-3fe3095b17073e3f59ac1a3c3bb8a221670eb9e2",
    urls = ["https://github.com/zaucy/rules_7zip/archive/3fe3095b17073e3f59ac1a3c3bb8a221670eb9e2.zip"],
    sha256 = "1ff64455e3321e916622d5dcaf354dfafe990b6c9427f1760055b0f15ad64a12",
)

load("@com_github_zaucy_rules_7zip//:setup.bzl", "setup_7zip")
setup_7zip()

C:\dev\repositories\osgi-manifest-compare>C:\temp\bazel-2.0.0-windows-x86_64.exe build -s //...
ERROR: C:/dev/repositories/osgi-manifest-compare/WORKSPACE:1:1: name 'http_archive' is not defined
ERROR: error loading package '': Encountered error while reading extension file 'setup.bzl': no such package '@com_github_zaucy_rules_7zip//': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'setup.bzl': no such package '@com_github_zaucy_rules_7zip//': error loading package 'external': Could not load //external package
INFO: Elapsed time: 1.102s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by zaucy** [comment]
You need to load in `http_archive` before hand :)

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
```

It's ony of bazel [embeded non-native rules](https://docs.bazel.build/versions/master/rules.html#embedded-non-native-rules). You can read about it here: https://docs.bazel.build/versions/master/repo/http.html#http_archive

**Comment by zaucy** [comment]
**As a side note:** It can be helpful to format your comments for other people to read when making issues on GitHub. Check out their *[Basic writing and formatting](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax)* specifically about *[Quoting code](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code)*

**Comment by zaucy** [comment]
I'm going to close this issue because I don't believe its a problem with rules_7zip. If you need more help please feel free to comment again :)
